create database OLAP_ANKIT_STG;

create TABLE OLAP_ANKIT_STG.CATEGORY (
	ID INT NOT NULL,
	CATEGORY_DESC VARCHAR(1024),
	primary key (ID)
);
create  TABLE OLAP_ANKIT_STG.COUNTRY (
	ID INT NOT NULL,
	COUNTRY_DESC VARCHAR(256),
	primary key (ID)
);
create  TABLE OLAP_ANKIT_STG.CUSTOMER (
	ID INT NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(256),
	CUSTOMER_MIDDLE_NAME VARCHAR(256),
	CUSTOMER_LAST_NAME VARCHAR(256),
	CUSTOMER_ADDRESS VARCHAR(256),
	primary key (ID)
);
create  TABLE OLAP_ANKIT_STG.SUBCATEGORY (
	ID INT NOT NULL,
	CATEGORY_ID INT,
	SUBCATEGORY_DESC VARCHAR(256),
	primary key (ID),
	foreign key (CATEGORY_ID) references OLAP_ANKIT_STG.CATEGORY(ID)
);
create  TABLE OLAP_ANKIT_STG.PRODUCT (
	ID INT NOT NULL,
	SUBCATEGORY_ID INT,
	PRODUCT_DESC VARCHAR(256),
	primary key (ID),
	foreign key (SUBCATEGORY_ID) references OLAP_ANKIT_STG.SUBCATEGORY(ID)
);


create  TABLE OLAP_ANKIT_STG.REGION (
	ID INT NOT NULL,
	COUNTRY_ID INT,
	REGION_DESC VARCHAR(256),
	primary key (ID),
	foreign key (COUNTRY_ID) references OLAP_ANKIT_STG.COUNTRY(ID)
);
create  TABLE OLAP_ANKIT_STG.STORE (
	ID INT NOT NULL,
	REGION_ID INT,
	STORE_DESC VARCHAR(256),
	primary key (ID),
	foreign key (REGION_ID) references OLAP_ANKIT_STG.REGION(ID)
);
create  TABLE OLAP_ANKIT_STG.SALES (
	ID INT NOT NULL,
	STORE_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	CUSTOMER_ID INT,
	TRANSACTION_TIME TIME,
	QUANTITY INT,
	AMOUNT INT,
	DISCOUNT INT,
	primary key (ID),
	foreign key (STORE_ID) references OLAP_ANKIT_STG.STORE(ID),
	foreign key (PRODUCT_ID) references OLAP_ANKIT_STG.PRODUCT(ID),
	foreign key (CUSTOMER_ID) references OLAP_ANKIT_STG.CUSTOMER(ID)
);



