create database OLTP_ANKIT;

create TABLE OLTP_ANKIT.CATEGORY (
	ID INT NOT NULL,
	CATEGORY_DESC VARCHAR(1024),
	primary key (ID)
);
create  TABLE OLTP_ANKIT.COUNTRY (
	ID INT NOT NULL,
	COUNTRY_DESC VARCHAR(256),
	primary key (ID)
);
create  TABLE OLTP_ANKIT.CUSTOMER (
	ID INT NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(256),
	CUSTOMER_MIDDLE_NAME VARCHAR(256),
	CUSTOMER_LAST_NAME VARCHAR(256),
	CUSTOMER_ADDRESS VARCHAR(256),
	primary key (ID)
);
create  TABLE OLTP_ANKIT.SUBCATEGORY (
	ID INT NOT NULL,
	CATEGORY_ID INT,
	SUBCATEGORY_DESC VARCHAR(256),
	primary key (ID),
	foreign key (CATEGORY_ID) references OLTP_ANKIT.CATEGORY(ID)
);
create  TABLE OLTP_ANKIT.PRODUCT (
	ID INT NOT NULL,
	SUBCATEGORY_ID INT,
	PRODUCT_DESC VARCHAR(256),
	primary key (ID),
	foreign key (SUBCATEGORY_ID) references OLTP_ANKIT.SUBCATEGORY(ID)
);
create  TABLE OLTP_ANKIT.REGION (
	ID INT NOT NULL,
	COUNTRY_ID INT,
	REGION_DESC VARCHAR(256),
	primary key (ID),
	foreign key (COUNTRY_ID) references OLTP_ANKIT.COUNTRY(ID)
);
create  TABLE OLTP_ANKIT.STORE (
	ID INT NOT NULL,
	REGION_ID INT,
	STORE_DESC VARCHAR(256),
	primary key (ID),
	foreign key (REGION_ID) references OLTP_ANKIT.REGION(ID)
);
create  TABLE OLTP_ANKIT.SALES (
	ID INT NOT NULL,
	STORE_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	CUSTOMER_ID INT,
	TRANSACTION_TIME TIMESTAMP,
	QUANTITY INT,
	AMOUNT INT,
	DISCOUNT INT,
	primary key (ID),
	foreign key (STORE_ID) references OLTP_ANKIT.STORE(ID),
	foreign key (PRODUCT_ID) references OLTP_ANKIT.PRODUCT(ID),
	foreign key (CUSTOMER_ID) references OLTP_ANKIT.CUSTOMER(ID)
);

create TABLE OLTP_ANKIT.SALES_v2 (
	ID int NOT NULL,
	STORE_ID int NOT NULL,
	PRODUCT_ID int NOT NULL,
	CUSTOMER_ID int NOT NULL,
	TRANSACTION_date date,
	QUANTITY int,
	AMOUNT int,
	DISCOUNT int,
	primary key (ID)
);

SELECT * FROM OLTP_ANKIT.CUSTOMER;
SELECT * FROM OLAP_ANKIT_STG.SALES;

SET GLOBAL local_infile = 1;

SHOW VARIABLES LIKE 'local_infile';

