#Tmp
CREATE DATABASE OLAP_ANKIT_TEMP;
create  TABLE OLAP_ANKIT_TEMP.AGG_SLS_PLC_MONTH (
  PDT_KY INT,
  STORE_KY INT,
  CTGRY_KY INT,
  MONTH_KY INT,
  TOTAL_QTY INT,
  TOTAL_AMT INT,
  TOTAL_DSCNT INT
);
create  TABLE OLAP_ANKIT_TEMP.CATEGORY (
  CTGRY_ID INT,
  CTGRY_DESC VARCHAR(50)
);
create  TABLE OLAP_ANKIT_TEMP.COUNTRY (
  CNTRY_ID INT,
  CNTRY_DESC VARCHAR(50)
);
create  TABLE OLAP_ANKIT_TEMP.CUSTOMER (
  CUSTOMER_ID INT,
  CUSTOMER_FST_NM VARCHAR(20),
  CUSTOMER_MID_NM VARCHAR(20),
  CUSTOMER_LST_NM VARCHAR(20),
  CUSTOMER_ADDR VARCHAR(20)
);
create  TABLE OLAP_ANKIT_TEMP.DAY (
  ID INT,
  MONTH_KY INT,
  QUARTER_KY INT,
  YEAR_KY INT,
  HALF_YEAR_KY INT,
  DAY_START_TIME TIME,
  DAY_END_TIME TIME
);
create  TABLE OLAP_ANKIT_TEMP.HALFYEAR (
  ID INT,
  YEAR_KY INT,
  HALF_YEAR_START_DATE DATE,
  HALF_YEAR_END_DATE DATE
);
create  TABLE OLAP_ANKIT_TEMP.HOUR (
  ID INT
);
create  TABLE OLAP_ANKIT_TEMP.MIN (
  ID INT,
  HOUR_KY INT
);
create  TABLE OLAP_ANKIT_TEMP.MONTH (
  ID INT,
  QUARTER_KY INT,
  YEAR_KY INT,
  HALF_YEAR_KY INT,
  MONTH_START_DATE DATE,
  MONTH_END_DATE DATE
);
create  TABLE OLAP_ANKIT_TEMP.PRODUCT (
  PDT_ID INT,
  SUB_CTGRY_KY INT,
  CTGRY_KY INT,
  PDT_DESC VARCHAR(50)
);
create  TABLE OLAP_ANKIT_TEMP.QUARTER (
  ID INT,
  YEAR_KY INT,
  HALF_YEAR_KY INT,
  QUARTER_START_DATE DATE,
  QUARTER_END_DATE DATE
);
create  TABLE OLAP_ANKIT_TEMP.REGION (
  RGN_ID INT,
  CNTRY_KY INT,
  RGN_DESC VARCHAR(50)
);
create  TABLE OLAP_ANKIT_TEMP.SALES (
  SLS_ID INT,
  STORE_KY INT,
  DT_KY DATE,
  PDT_KY INT,
  CUSTOMER_KY INT,
  TRANSACTION_TIME TIME,
  QTY INT,
  AMT INT,
  DSCNT INT
);
create  TABLE OLAP_ANKIT_TEMP.STORE (
  STORE_ID INT,
  RGN_KY INT,
  CNTRY_KY INT,
  STORE_DESC VARCHAR(50)
);
create  TABLE OLAP_ANKIT_TEMP.SUBCATEGORY (
  SUB_CTGRY_ID INT,
  CTGRY_KY INT,
  SUB_CTGRY_DESC VARCHAR(50)
);
create  TABLE OLAP_ANKIT_TEMP.YEAR (
  ID INT,
  YEAR_KY INT,
  YEAR_START_DATE DATE,
  YEAR_END_DATE DATE
);