DROP DATABASE OLAP_ANKIT_TGT;
create  database OLAP_ANKIT_TGT;

create  TABLE OLAP_ANKIT_TGT.D_RETAIL_CNTRY_T (
  CNTRY_ID INT,
  CNTRY_KY INT NOT NULL auto_increment,
  CNTRY_DESC VARCHAR(50),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint CNTRY_PK primary key (CNTRY_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_CTGRY_T (
  CTGRY_ID INT,
  CTGRY_KY INT NOT NULL auto_increment,
  CTGRY_DESC VARCHAR(50),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint CTGRY_PK primary key (CTGRY_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_CUSTOMER_T (
  CUSTOMER_ID INT,
  CUSTOMER_KY INT NOT NULL auto_increment,
  CUSTOMER_FST_NM VARCHAR(20),
  CUSTOMER_MID_NM VARCHAR(20),
  CUSTOMER_LST_NM VARCHAR(20),
  CUSTOMER_ADDR VARCHAR(20),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint CUSTOMER_PK primary key (CUSTOMER_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_LOCN_T (
  LOCN_ID INT,
  LOCN_KY INT NOT NULL auto_increment,
  RGN_KY INT,
  CNTRY_KY INT,
  LOCN_DESC VARCHAR(50),
  LAST_OPEN_TMS TIME,
  LAST_CLOSED_TMS TIME,
  ACTV_FLG VARCHAR(1),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint LOCN_PK primary key (LOCN_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_PDT_T (
  PDT_ID INT,
  PDT_KY INT NOT NULL auto_increment,
  SUB_CTGRY_KY INT,
  CTGRY_KY INT,
  PDT_DESC VARCHAR(50),
  PRICE INT,
  ACTV_FLG VARCHAR(1),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint PDT_PK primary key (PDT_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_RGN_T (
  RGN_ID INT,
  RGN_KY INT NOT NULL auto_increment,
  CNTRY_KY INT,
  RGN_DESC VARCHAR(50),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint RGN_PK primary key (RGN_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_SUB_CTGRY_T (
  SUB_CTGRY_ID INT,
  SUB_CTGRY_KY INT NOT NULL auto_increment,
  CTGRY_KY INT,
  SUB_CTGRY_DESC VARCHAR(50),
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint SUB_CTGRY_PK primary key (SUB_CTGRY_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_DAY_T (
  ID DATE NOT NULL,
  DT_KY DATE NOT NULL,
  MONTH_KY INT,
  QUARTER_KY INT NOT NULL,
  YEAR_KY INT NOT NULL,
  HALF_YEAR_KY INT NOT NULL,
  DAY_START_TIME TIME NOT NULL,
  DAY_END_TIME TIME NOT NULL,
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint DAY_PK primary key (DT_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_HALF_YEAR_T (
  ID INT NOT NULL,
  HALF_YEAR_KY INT NOT NULL,
  YEAR_KY INT NOT NULL,
  HALF_YEAR_START_DATE DATE NOT NULL,
  HALF_YEAR_END_DATE DATE NOT NULL,
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint HALF_YEAR_PK primary key (HALF_YEAR_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_HOUR_T (
  ID INT,
  HOUR_KY INT NOT NULL,
  constraint HOUR_PK primary key (HOUR_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_MIN_T (
  ID INT,
  MIN_KY INT NOT NULL,
  HOUR_KY INT,
  constraint MIN_PK primary key (MIN_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_MONTH_T (
  ID INT NOT NULL,
  MONTH_KY INT NOT NULL,
  MONTH_DESC INT NOT NULL,
  QUARTER_KY INT NOT NULL,
  YEAR_KY INT NOT NULL,
  HALF_YEAR_KY INT NOT NULL,
  MONTH_START_DATE DATE NOT NULL,
  MONTH_END_DATE DATE NOT NULL,
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint MONTH_PK primary key (MONTH_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_QUARTER_T (
  ID INT NOT NULL,
  QUARTER_KY INT NOT NULL,
  YEAR_KY INT NOT NULL,
  HALF_YEAR_KY INT NOT NULL,
  QUARTER_START_DATE DATE NOT NULL,
  QUARTER_END_DATE DATE NOT NULL,
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint QUARTER_PK primary key (QUARTER_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_SEC_T (
  ID INT,
  SEC_KY INT NOT NULL,
  MIN_KY INT,
  HOUR_KY INT,
  constraint SEC_PK primary key (SEC_KY)
);
create  TABLE OLAP_ANKIT_TGT.D_RETAIL_TIME_YEAR_T (
  ID INT,
  YEAR_KY INT NOT NULL,
  YEAR_START_DATE DATE NOT NULL,
  YEAR_END_DATE DATE NOT NULL,
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint YEAR_PK primary key (YEAR_KY)
);
create  TABLE OLAP_ANKIT_TGT.F_RETAIL_AGG_SLS_PLC_MONTH_T (
  ROW_KEY INT NOT NULL auto_increment,
  PDT_KY INT NOT NULL,
  LOCN_KY INT NOT NULL,
  MONTH_KY INT NOT NULL,
  TOTAL_QTY INT,
  TOTAL_AMT INT,
  TOTAL_DSCNT INT,
  ROW_INSRT_TMS TIME NOT NULL,
  ROW_UPDT_TMS TIME NOT NULL,
  constraint SLS_AGG_PK primary key (ROW_KEY)
);
create  TABLE OLAP_ANKIT_TGT.F_RETAIL_SLS_T (
  ROW_KEY INT NOT NULL auto_increment,
  SLS_ID INT NOT NULL,
  LOCN_KY INT,
  DT_KY DATE,
  PDT_KY INT,
  CUSTOMER_KY INT,
  TRANSACTION_TIME TIME,
  QTY INT,
  AMT INT,
  DSCNT INT,
  OPEN_CLOSE_CD VARCHAR(1),
  ROW_INSRT_TMS TIME,
  ROW_UPDT_TMS TIME,
  constraint SLS_PK primary key (ROW_KEY)
);

CREATE  TABLE OLAP_ANKIT_TGT.F_RETAIL_FRCST_SLS_T (
  DT_KY DATE,
  SLS_AMT_FCST INT
  );